---
# Source: osc-bsu-csi-driver/templates/csidriver.yaml
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: ebs.csi.aws.com
  labels:
    app.kubernetes.io/name: osc-bsu-csi-driver
spec:
  attachRequired: true
  podInfoOnMount: false
  fsGroupPolicy: File
