apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
- serviceaccount-csi-controller.yaml
- clusterrole-attacher.yaml
- clusterrole-provisioner.yaml
- clusterrole-resizer.yaml
- clusterrolebinding-attacher.yaml
- clusterrolebinding-provisioner.yaml
- clusterrolebinding-resizer.yaml
- node.yaml
- controller.yaml
- csidriver.yaml
