apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bsu-claim
  namespace: dynamic-p
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: bsu-sc
  resources:
    requests:
      storage: 4Gi
