FROM golang:1.17.6-buster

ARG DEBUG_IMAGE="disable"

RUN apt-get -y update && \
    apt-get -y --no-install-recommends install ca-certificates \
     										   e2fsprogs \
     										   xfsprogs \
     										   util-linux && \
    if [ "${DEBUG_IMAGE}" = "enable" ]; then \
	 	apt-get -y --no-install-recommends install gdb=7.12-6 jq=1.5+dfsg-1.3; \
		echo "add-auto-load-safe-path /usr/local/go/src/runtime/runtime-gdb.py" >> /root/.gdbinit; \
    fi && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver
