# Copyright 2019 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.15.6-buster

ARG DEBUG_IMAGE="disable"

RUN apt-get -y update && \
    if [ ${DEBUG_IMAGE} = "enable" ]; then \
        apt-get -y --no-install-recommends install gdb=7.12-6 jq=1.5+dfsg-1.3; \
        echo "add-auto-load-safe-path /usr/local/go/src/runtime/runtime-gdb.py" >> /root/.gdbinit; \
    fi && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /go/src/github.com/outscale-dev/osc-bsu-csi-driver
COPY . .

ENTRYPOINT ["./tester_entrypoint.sh"]
