apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-source-pvc
  namespace: my-source-namespace
spec:
  storageClassName: gp2-delete-immediate
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
