kind: Deployment
apiVersion: apps/v1
metadata:
  name: ebs-csi-controller
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: ebs-plugin
          env:
# region
            - name: AWS_REGION
              value: eu-west-2
# Max bsu limits
            - name: MAX_BSU_VOLUMES
              value: "25"
# integer in second defining initial duration
            - name: BACKOFF_DURATION
              value: "1"
# float define the factor multiplied by Duration each iteration
            - name: BACKOFF_FACTOR
              value: "1.9"
# integer defining the remaining number of iterations in which the duration parameter may change
            - name: BACKOFF_STEPS
              value: "20"
