{{- if .Values.enableVolumeResizing }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bsu-csi-resizer-binding
  labels:
    {{- include "osc-bsu-csi-driver.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: bsu-csi-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: bsu-external-resizer-role
  apiGroup: rbac.authorization.k8s.io

{{- end}}
