apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: ebs.csi.aws.com
  labels:
    {{- include "osc-bsu-csi-driver.labels" . | nindent 4 }}
spec:
  attachRequired: true
  podInfoOnMount: false
  fsGroupPolicy: {{ .Values.csiDriver.fsGroupPolicy }}
