# Node Service
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: osc-csi-node
  namespace: kube-system
  labels:
    {{- include "osc-bsu-csi-driver.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: osc-csi-node
      {{- include "osc-bsu-csi-driver.selectorLabels" . | nindent 6 }}
  updateStrategy:
    {{- toYaml .Values.node.updateStrategy | nindent 4 }}
  template:
    metadata:
      labels:
        app: osc-csi-node
        {{- include "osc-bsu-csi-driver.labels" . | nindent 8 }}
        {{- if .Values.node.podLabels }}
          {{ toYaml .Values.node.podLabels | nindent 8 }}
        {{- end }}
      {{- if .Values.node.podAnnotations }}
      annotations: {{ toYaml .Values.node.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      hostNetwork: true
      priorityClassName: system-node-critical
      tolerations:
        {{- if .Values.node.tolerateAllTaints }}
        - operator: Exists
        {{- else }}
        - key: CriticalAddonsOnly
          operator: Exists
        - operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
        {{- end }}
        {{- with .Values.node.tolerations }}
{{ toYaml . | indent 8 }}
        {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.node.securityContext }}
      securityContext:  
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: osc-plugin
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - node
            - --endpoint=$(CSI_ENDPOINT)
            - --logtostderr
            - --v={{ .Values.verbosity }}
          {{- range .Values.node.args }}
            - {{ . }}
          {{- end }}
          env:
            - name: CSI_ENDPOINT
              value: unix:/csi/csi.sock
            - name: BACKOFF_DURATION
              value: "{{ .Values.backoff.duration }}"
            - name: BACKOFF_FACTOR
              value: "{{ .Values.backoff.factor }}"
            - name: BACKOFF_STEPS
              value: "{{ .Values.backoff.steps }}"
            {{- if .Values.maxBsuVolumes }}
            - name: MAX_BSU_VOLUMES
              value: "{{ .Values.maxBsuVolumes }}"
            {{- end }}
          volumeMounts:
            - name: kubelet-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - name: plugin-dir
              mountPath: /csi
            - name: device-dir
              mountPath: /dev
          ports:
            - name: healthz
              containerPort: {{ .Values.sidecars.livenessProbeImage.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 5
          {{- if .Values.node.resources }}
            {{- with .Values.node.resources }}
          resources: {{ toYaml . | nindent 12 }}
            {{- end }}
          {{- else }}
            {{- with .Values.resources }}
          resources: {{ toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.node.containerSecurityContext }}
          securityContext:  
            {{- toYaml . | nindent 12 }}
          {{- end }}

        - name: node-driver-registrar
          image: {{ printf "%s:%s" .Values.sidecars.nodeDriverRegistrarImage.repository .Values.sidecars.nodeDriverRegistrarImage.tag }}
          args:
            - --csi-address=$(ADDRESS)
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
            - --v={{ .Values.verbosity }}
        {{- if .Values.sidecars.nodeDriverRegistrarImage.enableHttpEndpoint }}
            - --http-endpoint=:{{ .Values.sidecars.nodeDriverRegistrarImage.httpEndpointPort }}
        {{- end }}
        {{- if .Values.sidecars.nodeDriverRegistrarImage.enableHttpEndpoint }}
          ports:
            - name: httpendpoint
              containerPort: {{ .Values.sidecars.nodeDriverRegistrarImage.httpEndpointPort }}
              protocol: TCP
        {{- end }}
        {{- if and .Values.sidecars.nodeDriverRegistrarImage.enableHttpEndpoint .Values.sidecars.nodeDriverRegistrarImage.enableLivenessProbe }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: httpendpoint
              scheme: HTTP
        {{- end }}
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/bsu.csi.outscale.com/csi.sock
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
          {{- if .Values.sidecars.nodeDriverRegistrarImage.resources }}
            {{- with .Values.sidecars.nodeDriverRegistrarImage.resources }}
          resources: {{ toYaml . | nindent 12 }}
            {{- end }}
          {{- else if .Values.node.resources }}
            {{- with .Values.node.resources }}
          resources: {{ toYaml . | nindent 12 }}
            {{- end }}
          {{- else }}
            {{- with .Values.resources }}
          resources: {{ toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.sidecars.nodeDriverRegistrarImage.securityContext }}
          securityContext:  
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: liveness-probe
          image: {{ printf "%s:%s" .Values.sidecars.livenessProbeImage.repository .Values.sidecars.livenessProbeImage.tag }}
          args:
            - --csi-address=/csi/csi.sock
            - --health-port={{ .Values.sidecars.livenessProbeImage.port }}
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
          {{- if .Values.sidecars.livenessProbeImage.resources }}
            {{- with .Values.sidecars.livenessProbeImage.resources }}
          resources: {{ toYaml . | nindent 12 }}
            {{- end }}
          {{- else if .Values.node.resources }}
            {{- with .Values.node.resources }}
          resources: {{ toYaml . | nindent 12 }}
            {{- end }}
          {{- else }}
            {{- with .Values.resources }}
          resources: {{ toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.sidecars.livenessProbeImage.securityContext }}
          securityContext:  
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/bsu.csi.outscale.com/
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory
