apiVersion: v1
kind: ServiceAccount
metadata:
  name: osc-csi-controller-sa
  namespace: kube-system
  labels:
    {{- include "osc-bsu-csi-driver.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.controller.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}