apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bsu-claim
  namespace: resizing-p
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: resize-sc
  resources:
    requests:
      storage: 4Gi
