{{- if .Values.cloud.credentials.create }}
{{- if not .Values.cloud.credentials.accessKey }}
{{- fail "You must specify an API access key in cloud.credentials.accessKey" }}
{{- end }}
{{- if not .Values.cloud.credentials.secretKey }}
{{- fail "You must specify an API secret key in cloud.credentials.secretKey" }}
{{- end }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.cloud.credentials.secretName }}
  labels:
    {{- include "osc-bsu-csi-driver.labels" . | nindent 4 }}
stringData:
  access_key: {{ .Values.cloud.credentials.accessKey | quote }}
  secret_key: {{ .Values.cloud.credentials.secretKey | quote }}
{{- else }}
# Using user-specified secret {{ .Values.cloud.credentials.secretName }}
{{- end }}