apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../snapshotter
namespace: kube-system

images:
- name: outscale/osc-ebs-csi-driver
  newTag: v0.0.14beta
  newName: outscale/osc-ebs-csi-driver
- name: k8s.gcr.io/sig-storage/csi-provisioner
  newTag: v3.0.0
  newName: k8s.gcr.io/sig-storage/csi-provisioner
- name: k8s.gcr.io/sig-storage/csi-attacher
  newTag: v3.3.0
  newName: k8s.gcr.io/sig-storage/csi-attacher
- name: k8s.gcr.io/sig-storage/csi-snapshotter
  newTag: v4.2.1
  newName: k8s.gcr.io/sig-storage/csi-snapshotter
- name: k8s.gcr.io/sig-storage/livenessprobe
  newTag: v2.5.0
  newName: k8s.gcr.io/sig-storage/livenessprobe
- name: k8s.gcr.io/sig-storage/csi-resizer
  newTag: v1.3.0
  newName: k8s.gcr.io/sig-storage/csi-resizer
- name: k8s.gcr.io/sig-storage/csi-node-driver-registrar
  newTag: v2.3.0
  newName: k8s.gcr.io/sig-storage/csi-node-driver-registrar
- name: k8s.gcr.io/sig-storage/snapshot-controller
  newTag: v3.0.3
  newName: k8s.gcr.io/sig-storage/snapshot-controller

patches:
   - target:
       kind: DaemonSet
# imagePullSecrets (dockerconfig secret)
     patch: |-
       - op: replace
         path: /spec/template/spec/imagePullSecrets
         value: [{ name: registry-dockerconfigjson }]
   - target:
       kind: Deployment
# imagePullSecrets (dockerconfig secret)
     patch: |-
       - op: replace
         path: /spec/template/spec/imagePullSecrets
         value: [{ name: registry-dockerconfigjson }]

patchesStrategicMerge:
# set the verbosity level of plugins and timeout for sidecars
- verbosity_timeout.yaml
# Add ebs-plugin env
- backoff.yaml
# enable volume snapshot
- csi_resizer.yaml
- csi_snapshotter.yaml
