apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bsu-snapshot-restored-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: bsu-sc
  resources:
    requests:
      storage: 4Gi
  dataSource:
    name: bsu-volume-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
