#!/bin/bash

# Copyright 2019 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

AWS_K8S_TESTER_PATH=/bin/osc-k8s-tester

if [ "$BUILD_TESTER" = "enabled" ]; then
    if [ -z "$TESTER_BRANCH" ]; then
        TESTER_BRANCH="poc"
    fi
    rm -rf /go/src/github.com/aws/aws-k8s-tester
    git clone -b $TESTER_BRANCH https://github.com/outscale-dev/osc-k8s-tester.git /go/src/github.com/aws/aws-k8s-tester
    cd /go/src/github.com/aws/aws-k8s-tester
    make -j 4
    cp /go/src/github.com/aws/aws-k8s-tester/bin/aws-k8s-tester-*-linux-* /bin/osc-k8s-tester
fi

VPC_ID_FLAG=""
if [ -z "$AWS_K8S_TESTER_VPC_ID" ]; then
    VPC_ID_FLAG=--vpc-id=${AWS_K8S_TESTER_VPC_ID}
fi

PR_NUM_FLAG=""
if [ -z "$PULL_NUMBER" ]; then
    PR_NUM_FLAG=--pr-num=${PULL_NUMBER}
fi

chmod +x ${AWS_K8S_TESTER_PATH}

${AWS_K8S_TESTER_PATH} csi test integration --terminate-on-exit=true --timeout=20m ${PR_NUM_FLAG} ${VPC_ID_FLAG}
