kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: bsu-sc-encrypted
  namespace: encryption
provisioner: bsu.csi.outscale.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  encrypted: 'true'
  luks-cipher: aes-xts-plain64
  type: io1
  iopsPerGB: '50'
  csi.storage.k8s.io/node-stage-secret-name: luks-key
  csi.storage.k8s.io/node-stage-secret-namespace: encryption
  csi.storage.k8s.io/node-expand-secret-name: luks-key
  csi.storage.k8s.io/node-expand-secret-namespace: encryption