kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: bsu-sc
provisioner: bsu.csi.outscale.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: io1
  iopsPerGB: "50"
allowedTopologies:
- matchLabelExpressions:
  - key: topology.bsu.csi.outscale.com/zone
    values:
    - eu-west-2a
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bsu-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: bsu-sc
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: bsu-claim
