apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: static-snapshot-content
spec:
  volumeSnapshotRef:
    kind: VolumeSnapshot
    name: static-snapshot-demo
    namespace: default 
  source:
    snapshotHandle: snap-0fba4d7649d765c50
  driver: bsu.csi.outscale.com
  volumeSnapshotClassName: csi-osc-vsc
