kind: VolumeAttributesClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: bsu-vac
provisioner: bsu.csi.outscale.com
parameters:
  iopspergb: "500"
  volumeType: "io1"
---
kind: VolumeAttributesClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: bsu-vac-after
provisioner: bsu.csi.outscale.com
parameters:
  iopspergb: "1000"
  volumeType: "io1"
