FROM golang:1.19-buster

RUN curl -o /usr/local/bin/kubectl -LO https://storage.googleapis.com/kubernetes-release/release/v1.24.10/bin/linux/amd64/kubectl && chmod +x /usr/local/bin/kubectl
RUN export GO111MODULE=on && export PATH=$PATH:/usr/local/go/bin && export GOPATH="/go" && go install "github.com/onsi/ginkgo/v2/ginkgo@v2.8.1"

WORKDIR $GOPATH/src/cloud-provider-osc

