FROM golang:1.17.6-buster

RUN curl -o /usr/local/bin/kubectl -LO https://storage.googleapis.com/kubernetes-release/release/v1.21.5/bin/linux/amd64/kubectl && chmod +x /usr/local/bin/kubectl
RUN export GO111MODULE=on && export PATH=$PATH:/usr/local/go/bin && export GOPATH="/go" && go get -v -u "github.com/onsi/ginkgo/ginkgo@v1.16.4"

WORKDIR /root/aws-ebs-csi-driver

