name: Build

on:
  pull_request:
    branches:
      - OSC-MIGRATION
      - main
    paths:
      - "**.go"
      - "**.yaml"
      - "Dockerfile"
      - ".trivyignore"
      - "Makefile"
      - "go.*"
      - ".github/workflows/build.yml"
      - "!tests/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@v6
    - name: 🔎 Docker lint
      run: bash -c "make dockerlint"
    - name: 🔎 golangci-lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.6.0
        args: --timeout=300s
        only-new-issues: true
    - name: 🔎 Reuse check
      run: make lint-reuse
  unit-test:
    runs-on: ubuntu-22.04
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@v6
    - name: ⬇️ Install Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
    - name: 🧪 Test
      run: make test
    - name: 🧪 Sanity test
      run: make test-sanity
  docs:
    runs-on: ubuntu-22.04
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@v6
    - name: 🔎 Check docs
      run: bash -c "make check-helm-docs"
  trivy:
    runs-on: ubuntu-22.04
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@v6
    - name: 📦 Build image
      run: bash -c "make build-image"
    - name: 🔎 Trivy-Scan
      run: bash -c "make trivy-scan"
    - name: 🔎 Trivy-Ignore-Check
      run: bash -c "make trivy-ignore-check"
    - name: ⬆️ Upload result
      if: ${{ always() && github.event_name != 'pull_request' }}
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: './.trivyscan/report.sarif'
