name: Build

on:
  pull_request:
    branches:
      - OSC-MIGRATION
      - main
    paths:
      - "**.go"
      - "**.yaml"
      - "Dockerfile"
      - ".trivyignore"
      - "Makefile"
      - "go.*"
      - ".github/workflows/build.yml"
      - "!tests/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - name: 🔎 Docker lint
      run: bash -c "make dockerlint"
    - name: 🔎 golangci-lint
      uses: outscale/goutils/.github/actions/lint@8a4f7b08b35c0c071190ecca48362a3c3cd5a190 # main
    - name: 🔎 Reuse check
      run: make lint-reuse
  unit-test:
    runs-on: ubuntu-22.04
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - name: ⬇️ Install Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
      with:
        go-version-file: 'go.mod'
    - name: 🧪 Test
      run: make test
  docs:
    runs-on: ubuntu-22.04
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - name: 🔎 Check docs
      run: bash -c "make check-helm-docs"
