name: Build

on:
  pull_request:
    branches:
      - OSC-MIGRATION
      - main
    paths:
      - "**.go"
      - "**.yaml"
      - "Dockerfile"
      - ".trivyignore"
      - "Makefile"
      - "go.*"
      - ".github/workflows/build.yml"
      - "!tests/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: 🔎 Docker lint
      run: bash -c "make dockerlint"
    - name: 🔎 golangci-lint
      uses: outscale/goutils/.github/actions/lint@ba9b0e7bcc1ab4b8fd2c69d8b4de17d86218f5b5 # v1.0.0
    - name: 🔎 Reuse check
      run: make lint-reuse
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: ⬇️ Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: 'go.mod'
    - name: 🧪 Test
      run: make test
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: 🔎 Check docs
      run: bash -c "make check-helm-docs"
