name: E2E

on:
  pull_request:
    branches:
      - OSC-MIGRATION
      - main
    paths:
      - "**.go"
      - "Dockerfile"
      - "Makefile"
      - "go.*"
      - "helm/osc-bsu-csi-driver/**.yaml"
      - ".github/workflows/e2e.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sanity:
    runs-on: [self-hosted, linux]
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: 🔐 Set ak/sk name based on runner region
      run: .github/scripts/runneraksk.sh
    - name: ⬇️ Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: 'go.mod'
    - name: 🧹 Frieza
      uses: outscale/frieza-github-actions/frieza-clean@1a8eba5199913da60ae6d92d6050e17410186a38 # v0.16.1+hotfix.0
      with:
        access_key: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        secret_key: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        region: ${{ env.OSC_REGION }}
        exclude_resource_types: access_key
    - name: 🧪 Sanity test
      run:
        make test-sanity
      env:
        OSC_ACCESS_KEY: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        OSC_SECRET_KEY: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        OSC_REGION: ${{ env.OSC_REGION }}
  e2e:
    runs-on: [self-hosted, linux]
    needs: [sanity]
    steps:
    - name: ⬇️ Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: 🔐 Set ak/sk name based on runner region
      run: .github/scripts/runneraksk.sh
    - name: ⬇️ Install kubectl
      uses: azure/setup-kubectl@829323503d1be3d00ca8346e5391ca0b07a9ab0d # v5.1.0
      with:
        version: v1.34.9
    - name: ⬇️ Install helm
      uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1
      with:
        version: v3.21.3
    - name: ⬇️ Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: 'go.mod'
    - name: ⬇️ Set up Docker Buildx
      uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
    - name: 🧹 Frieza
      uses: outscale/frieza-github-actions/frieza-clean@1a8eba5199913da60ae6d92d6050e17410186a38 # v0.16.1+hotfix.0
      with:
        access_key: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        secret_key: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        region: ${{ env.OSC_REGION }}
    - name: 👷 Deploy test cluster
      id: caposc
      uses: outscale/cluster-api-provider-outscale/.github/actions/deploy_cluster@7ddc5fd22c49ce7216e9321c2fe254e2d8e5f92d # v1.5.2
      with:
        RUNNER_NAME: ${{ runner.name }}
        OKS_ACCESS_KEY: ${{ secrets.OKS_ACCESS_KEY }}
        OKS_SECRET_KEY: ${{ secrets.OKS_SECRET_KEY }}
        OKS_REGION: ${{ vars.OKS_REGION }}
        OSC_ACCESS_KEY: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        OSC_SECRET_KEY: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        OSC_REGION: ${{ env.OSC_REGION }}
        CLUSTER_NAME: "csi"
        IMAGE_NAME: ${{ vars.IMG_MANAGEMENT }}
        CCM: true
        KUSTOMIZE_PATH: "tests/e2e/capi-kustomize"
    - name: 🐳 Login to Harbor
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        registry: ${{ vars.REGISTRY }}
        username: admin
        password: ${{ secrets.HARBOR_ADMIN_PASSWORD }}
    - name: 📦 Run GoReleaser
      uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
      with:
        version: 'v2.15.4'
        args: release --clean --snapshot
    - name: 📦 Push the Docker image
      run: |
        make image-tag image-push
      env:
        IMAGE: "outscale/osc-bsu-csi-driver"
        IMAGE_TAG: "${{ github.sha }}-amd64"
        REGISTRY_IMAGE: "${{ vars.REGISTRY }}/outscale/csi"
        REGISTRY_TAG: ${{ github.sha }}
    - name: 👷 Install CSI
      run: |
        kubectl create secret generic osc-csi-bsu --from-literal=access_key=$OSC_ACCESS_KEY --from-literal=secret_key=$OSC_SECRET_KEY -n kube-system
        kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-8.3/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
        kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-8.3/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
        kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-8.3/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
        kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-8.3/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
        kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-8.3/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
        make helm_deploy
      env:
        KUBECONFIG: "${{ github.workspace }}/${{ steps.caposc.outputs.KUBECONFIG }}"
        OSC_ACCESS_KEY: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        OSC_SECRET_KEY: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        OSC_REGION: ${{ env.OSC_REGION}}
        TARGET_IMAGE: "${{ vars.REGISTRY }}/outscale/csi"
        TARGET_TAG: ${{ github.sha }}
    - name: 🧪 Run e2e tests
      run: make test-e2e
      env:
        KUBECONFIG: "${{ github.workspace }}/${{ steps.caposc.outputs.KUBECONFIG }}"
        OSC_ACCESS_KEY: ${{ secrets[env.OSC_ACCESS_KEY_NAME] }}
        OSC_SECRET_KEY: ${{ secrets[env.OSC_SECRET_KEY_NAME] }}
        OSC_REGION: ${{ env.OSC_REGION }}
        AWS_AVAILABILITY_ZONES: ${{ env.OSC_SUBREGION_NAME }}
