name: Trivy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/trivy.yml"
  schedule:
    - cron: "26 6 * * 0"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: 📦 Build   Docker Image
        run: |
          make build-image
        env:
          IMAGE_TAG: ${{ github.sha }}

      - name: 🔎 Trivy-Scan
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: outscale/osc-bsu-csi-driver:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          trivyignores: '.trivyignore'
          version: 'v0.69.3'

      - name: ⬆️ Upload Trivy results
        if: ${{ github.event_name != 'pull_request' }}
        uses: github/codeql-action/upload-sarif@c10b8064de6f491fea524254123dbe5e09572f13 # v4
        with:
          sarif_file: 'trivy-results.sarif'
