// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/outscale-dev/osc-bsu-csi-driver/pkg/cloud (interfaces: OscInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	osc "github.com/outscale/osc-sdk-go/v2"
)

// MockOscInterface is a mock of OscInterface interface.
type MockOscInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOscInterfaceMockRecorder
}

// MockOscInterfaceMockRecorder is the mock recorder for MockOscInterface.
type MockOscInterfaceMockRecorder struct {
	mock *MockOscInterface
}

// NewMockOscInterface creates a new mock instance.
func NewMockOscInterface(ctrl *gomock.Controller) *MockOscInterface {
	mock := &MockOscInterface{ctrl: ctrl}
	mock.recorder = &MockOscInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOscInterface) EXPECT() *MockOscInterfaceMockRecorder {
	return m.recorder
}

// CreateSnapshot mocks base method.
func (m *MockOscInterface) CreateSnapshot(arg0 context.Context, arg1 osc.CreateSnapshotRequest) (osc.CreateSnapshotResponse, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSnapshot", arg0, arg1)
	ret0, _ := ret[0].(osc.CreateSnapshotResponse)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateSnapshot indicates an expected call of CreateSnapshot.
func (mr *MockOscInterfaceMockRecorder) CreateSnapshot(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSnapshot", reflect.TypeOf((*MockOscInterface)(nil).CreateSnapshot), arg0, arg1)
}

// CreateTags mocks base method.
func (m *MockOscInterface) CreateTags(arg0 context.Context, arg1 osc.CreateTagsRequest) (osc.CreateTagsResponse, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTags", arg0, arg1)
	ret0, _ := ret[0].(osc.CreateTagsResponse)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateTags indicates an expected call of CreateTags.
func (mr *MockOscInterfaceMockRecorder) CreateTags(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTags", reflect.TypeOf((*MockOscInterface)(nil).CreateTags), arg0, arg1)
}

// CreateVolume mocks base method.
func (m *MockOscInterface) CreateVolume(arg0 context.Context, arg1 osc.CreateVolumeRequest) (osc.CreateVolumeResponse, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVolume", arg0, arg1)
	ret0, _ := ret[0].(osc.CreateVolumeResponse)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateVolume indicates an expected call of CreateVolume.
func (mr *MockOscInterfaceMockRecorder) CreateVolume(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVolume", reflect.TypeOf((*MockOscInterface)(nil).CreateVolume), arg0, arg1)
}

// DeleteSnapshot mocks base method.
func (m *MockOscInterface) DeleteSnapshot(arg0 context.Context, arg1 osc.DeleteSnapshotRequest) (osc.DeleteSnapshotResponse, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSnapshot", arg0, arg1)
	ret0, _ := ret[0].(osc.DeleteSnapshotResponse)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteSnapshot indicates an expected call of DeleteSnapshot.
func (mr *MockOscInterfaceMockRecorder) DeleteSnapshot(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSnapshot", reflect.TypeOf((*MockOscInterface)(nil).DeleteSnapshot), arg0, arg1)
}

// DeleteVolume mocks base method.
func (m *MockOscInterface) DeleteVolume(arg0 context.Context, arg1 osc.DeleteVolumeRequest) (osc.DeleteVolumeResponse, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVolume", arg0, arg1)
	ret0, _ := ret[0].(osc.DeleteVolumeResponse)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteVolume indicates an expected call of DeleteVolume.
func (mr *MockOscInterfaceMockRecorder) DeleteVolume(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVolume", reflect.TypeOf((*MockOscInterface)(nil).DeleteVolume), arg0, arg1)
}

// LinkVolume mocks base method.
func (m *MockOscInterface) LinkVolume(arg0 context.Context, arg1 osc.LinkVolumeRequest) (osc.LinkVolumeResponse, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkVolume", arg0, arg1)
	ret0, _ := ret[0].(osc.LinkVolumeResponse)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LinkVolume indicates an expected call of LinkVolume.
func (mr *MockOscInterfaceMockRecorder) LinkVolume(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkVolume", reflect.TypeOf((*MockOscInterface)(nil).LinkVolume), arg0, arg1)
}

// ReadSnapshots mocks base method.
func (m *MockOscInterface) ReadSnapshots(arg0 context.Context, arg1 osc.ReadSnapshotsRequest) (osc.ReadSnapshotsResponse, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSnapshots", arg0, arg1)
	ret0, _ := ret[0].(osc.ReadSnapshotsResponse)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadSnapshots indicates an expected call of ReadSnapshots.
func (mr *MockOscInterfaceMockRecorder) ReadSnapshots(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSnapshots", reflect.TypeOf((*MockOscInterface)(nil).ReadSnapshots), arg0, arg1)
}

// ReadSubregions mocks base method.
func (m *MockOscInterface) ReadSubregions(arg0 context.Context, arg1 osc.ReadSubregionsRequest) (osc.ReadSubregionsResponse, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSubregions", arg0, arg1)
	ret0, _ := ret[0].(osc.ReadSubregionsResponse)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadSubregions indicates an expected call of ReadSubregions.
func (mr *MockOscInterfaceMockRecorder) ReadSubregions(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSubregions", reflect.TypeOf((*MockOscInterface)(nil).ReadSubregions), arg0, arg1)
}

// ReadVms mocks base method.
func (m *MockOscInterface) ReadVms(arg0 context.Context, arg1 osc.ReadVmsRequest) (osc.ReadVmsResponse, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadVms", arg0, arg1)
	ret0, _ := ret[0].(osc.ReadVmsResponse)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadVms indicates an expected call of ReadVms.
func (mr *MockOscInterfaceMockRecorder) ReadVms(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadVms", reflect.TypeOf((*MockOscInterface)(nil).ReadVms), arg0, arg1)
}

// ReadVolumes mocks base method.
func (m *MockOscInterface) ReadVolumes(arg0 context.Context, arg1 osc.ReadVolumesRequest) (osc.ReadVolumesResponse, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadVolumes", arg0, arg1)
	ret0, _ := ret[0].(osc.ReadVolumesResponse)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadVolumes indicates an expected call of ReadVolumes.
func (mr *MockOscInterfaceMockRecorder) ReadVolumes(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadVolumes", reflect.TypeOf((*MockOscInterface)(nil).ReadVolumes), arg0, arg1)
}

// UnlinkVolume mocks base method.
func (m *MockOscInterface) UnlinkVolume(arg0 context.Context, arg1 osc.UnlinkVolumeRequest) (osc.UnlinkVolumeResponse, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkVolume", arg0, arg1)
	ret0, _ := ret[0].(osc.UnlinkVolumeResponse)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UnlinkVolume indicates an expected call of UnlinkVolume.
func (mr *MockOscInterfaceMockRecorder) UnlinkVolume(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkVolume", reflect.TypeOf((*MockOscInterface)(nil).UnlinkVolume), arg0, arg1)
}

// UpdateVolume mocks base method.
func (m *MockOscInterface) UpdateVolume(arg0 context.Context, arg1 osc.UpdateVolumeRequest) (osc.UpdateVolumeResponse, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVolume", arg0, arg1)
	ret0, _ := ret[0].(osc.UpdateVolumeResponse)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateVolume indicates an expected call of UpdateVolume.
func (mr *MockOscInterfaceMockRecorder) UpdateVolume(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVolume", reflect.TypeOf((*MockOscInterface)(nil).UpdateVolume), arg0, arg1)
}
